"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prompt_code_assist = prompt_code_assist;
// Generated by MarrowScript compiler. DO NOT EDIT.
const logger_1 = require("../logger");
const metrics_1 = require("../metrics");
const budget_1 = require("./budget");
const validate_1 = require("./validate");
const traces_1 = require("./traces");
const repair_1 = require("./repair");
const router_1 = require("./router");
const prompts_helpers_1 = require("./prompts_helpers");
// Prompt: code_assist
// model: router:coding_router
// validate: schema_only | on_invalid: retry_with_repair_prompt | timeout: 120000ms
async function prompt_code_assist(input, ctx) {
    const __start = Date.now();
    const __router = (0, router_1.getRouter)("coding_router");
    const __routeChoice = __router.route(input);
    let __model = __routeChoice.model;
    let __tier = __routeChoice.tier;
    const __template = (0, prompts_helpers_1.loadExtension)("tmpl_code_assist");
    const __rendered = String(__template(...Object.values(input)));
    const __messages = [{ role: "user", content: __rendered }];
    const __budget = ctx.budget ?? (0, budget_1.newBudget)(ctx.trace_id);
    const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
    const __maxAttempts = 3;
    let __lastError = null;
    for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
        const __controller = new AbortController();
        const __timer = setTimeout(() => __controller.abort(), 120000);
        if (ctx.signal)
            ctx.signal.addEventListener("abort", () => __controller.abort());
        try {
            (0, metrics_1.counter)("cognition.prompt_calls", { prompt: "code_assist", model: __model.name });
            // Budget gate — refuse if this attempt would push the trace over either ceiling.
            __budget.assertCanSpend(__estimatedTokens, __model.costClass);
            const __resp = await __model.provider.chat({
                model: __model.modelName,
                messages: __messages,
                temperature: __model.temperature,
                top_p: __model.topP ?? undefined,
                max_output: __model.maxOutput,
                stop: __model.stop,
                json: false,
            }, __controller.signal);
            clearTimeout(__timer);
            const __value = (0, prompts_helpers_1.parseModelOutput)(__resp.content, "string");
            // Phase 7: low-confidence check (router=coding_router, threshold=0.6, on_low_confidence=escalate)
            const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
            if (__confidence !== null && __confidence < 0.6) {
                (0, metrics_1.counter)("cognition.low_confidence", { prompt: "code_assist", model: __model.name });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "low_confidence",
                    kind: "low_confidence",
                    prompt: "code_assist",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    output: __value,
                    confidence: __confidence,
                    prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                    completion_tokens: __resp.usage.completion_tokens ?? undefined,
                    latency_ms: Date.now() - __start,
                    status: "low_confidence",
                    metadata: { threshold: 0.6, on_low_confidence: "escalate", attempt: __attempt, tier: __tier },
                });
                const __lcErr = new Error("low confidence: " + __confidence.toFixed(3) + " < 0.6");
                __lcErr.__validationIssues = ["confidence " + __confidence.toFixed(3) + " < 0.6"];
                __lcErr.__badOutput = __value;
                __lcErr.__lowConfidence = __confidence;
                throw __lcErr;
            }
            // validate: schema_only — structural check against string
            const __report = (0, validate_1.validateSchemaOnly)(__value, "string");
            if (!__report.ok) {
                const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
                __vErr.__validationIssues = __report.issues;
                __vErr.__badOutput = __value;
                throw __vErr;
            }
            const __elapsed = Date.now() - __start;
            // Phase 3: actual usage — refund the over-estimate, charge the truth.
            const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
            // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
            __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
            (0, metrics_1.histogram)("cognition.prompt_latency_ms", __elapsed, { prompt: "code_assist", model: __model.name });
            logger_1.logger.info("cognition_prompt_ok", {
                event: "code_assist",
                status: "success",
                duration_ms: __elapsed,
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
            });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "code_assist",
                step: "chat",
                kind: "prompt_call",
                prompt: "code_assist",
                model: __model.name,
                provider: __model.provider.name,
                input,
                output: __value,
                validate_result: "ok",
                confidence: __confidence ?? undefined,
                prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
                completion_tokens: __resp.usage.completion_tokens ?? undefined,
                latency_ms: __elapsed,
                cache_hit: false,
                status: "ok",
                metadata: { attempt: __attempt, tier: __tier },
            });
            return __value;
        }
        catch (__err) {
            clearTimeout(__timer);
            __lastError = __err;
            // Budget exceptions are terminal — no retry, no escalate, just bubble.
            if (__err instanceof budget_1.BudgetExceededError) {
                logger_1.logger.error("cognition_budget_exceeded", {
                    event: "code_assist",
                    status: "rejected",
                    trace_id: ctx.trace_id,
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
                });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "budget",
                    kind: "budget_exceeded",
                    prompt: "code_assist",
                    model: __model.name,
                    provider: __model.provider.name,
                    input,
                    latency_ms: Date.now() - __start,
                    status: "budget_exceeded",
                    error_code: "BUDGET_EXCEEDED",
                    metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
                });
                throw __err;
            }
            (0, metrics_1.counter)("cognition.prompt_failed", { prompt: "code_assist", model: __model.name });
            const __msg = __err instanceof Error ? __err.message : String(__err);
            logger_1.logger.warn("cognition_prompt_failed", {
                event: "code_assist",
                status: "rejected",
                trace_id: ctx.trace_id,
                metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
            });
            {
                const __issues = __err.__validationIssues;
                const __isValidate = Array.isArray(__issues);
                const __isLowConf = typeof __err.__lowConfidence === "number";
                const __badOut = __err.__badOutput;
                if (!__isLowConf) {
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "code_assist",
                        step: __isValidate ? "validate" : "chat",
                        kind: __isValidate ? "validate" : "prompt_call",
                        prompt: "code_assist",
                        model: __model.name,
                        provider: __model.provider.name,
                        input,
                        output: __isValidate ? __badOut : undefined,
                        validate_result: __isValidate ? "failed" : undefined,
                        latency_ms: Date.now() - __start,
                        status: __isValidate ? "validate_failed" : "provider_error",
                        error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
                        metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
                    });
                }
            }
            // on_invalid: retry_with_repair_prompt — single-shot repair via the same model
            {
                const __issues = __err.__validationIssues ?? [];
                if (__issues.length === 0) {
                    // Non-validation error — fall through to a normal retry.
                }
                else {
                    const __repairFn = repair_1.REPAIRS["code_assist"];
                    if (__repairFn) {
                        const __repair = await __repairFn({
                            original_input: input,
                            bad_output: __err && __err.__badOutput,
                            issues: __issues,
                        }, { trace_id: ctx.trace_id, signal: ctx.signal });
                        if (__repair.ok && __repair.value !== null) {
                            try {
                                const __repaired = (0, prompts_helpers_1.parseModelOutput)(String(__repair.value), "string");
                                // Re-validate the repaired output. We only accept it if it passes.
                                const __reReport = (0, validate_1.validateSchemaOnly)(__repaired, "string");
                                if (__reReport.ok) {
                                    __budget.charge(__repair.tokens_used || 0, __model.costClass);
                                    (0, metrics_1.counter)("cognition.repair.accepted", { prompt: "code_assist" });
                                    logger_1.logger.info("cognition_repair_accepted", { event: "code_assist", status: "success", trace_id: ctx.trace_id });
                                    await (0, traces_1.writeSpan)({
                                        trace_id: ctx.trace_id,
                                        workflow: "code_assist",
                                        step: "repair",
                                        kind: "repair",
                                        prompt: "code_assist",
                                        model: __model.name,
                                        provider: __model.provider.name,
                                        input,
                                        output: __repaired,
                                        validate_result: "ok",
                                        completion_tokens: __repair.tokens_used || undefined,
                                        latency_ms: Date.now() - __start,
                                        status: "repair_accepted",
                                        metadata: { issues_count: __issues.length, attempt: __attempt },
                                    });
                                    return __repaired;
                                }
                                (0, metrics_1.counter)("cognition.repair.rejected", { prompt: "code_assist" });
                                await (0, traces_1.writeSpan)({
                                    trace_id: ctx.trace_id,
                                    workflow: "code_assist",
                                    step: "repair",
                                    kind: "repair",
                                    prompt: "code_assist",
                                    model: __model.name,
                                    provider: __model.provider.name,
                                    input,
                                    output: __repaired,
                                    validate_result: "failed",
                                    completion_tokens: __repair.tokens_used || undefined,
                                    latency_ms: Date.now() - __start,
                                    status: "repair_rejected",
                                    metadata: { issues_count: __issues.length, re_issues: __reReport.issues.slice(0, 5) },
                                });
                            }
                            catch (__parseErr) {
                                (0, metrics_1.counter)("cognition.repair.unparseable", { prompt: "code_assist" });
                            }
                        }
                    }
                }
                // Repair failed (or no repair available) — fall through to next attempt.
            }
            if (__attempt < __maxAttempts)
                await new Promise(r => setTimeout(r, 1000 * Math.pow(2, __attempt - 1)));
        }
    }
    // Last-chance fallback escalation: local model exhausted retries.
    //   1. Find the router's fallback model.
    //   2. If it's distinct from the model that just failed, retry once
    //      with the fallback model + a fresh repair attempt budget.
    //   3. Emit a span tagged escalate / fallback so traces show the swap.
    {
        const __fb = __router.fallback();
        // Only swap if the fallback differs from the model that just failed.
        // Compare by name since the router never exposes a stable id at runtime.
        if (__fb && __fb.model.name !== __model.name) {
            (0, metrics_1.counter)("cognition.fallback.attempted", { prompt: "code_assist", from_model: __model.name, to_model: __fb.model.name });
            logger_1.logger.info("cognition_fallback_attempt", { event: "code_assist", status: "success", trace_id: ctx.trace_id, metadata: { from_model: __model.name, to_model: __fb.model.name, after_attempts: __maxAttempts } });
            await (0, traces_1.writeSpan)({
                trace_id: ctx.trace_id,
                workflow: "code_assist",
                step: "fallback",
                kind: "escalate",
                prompt: "code_assist",
                model: __fb.model.name,
                provider: __fb.model.provider.name,
                latency_ms: Date.now() - __start,
                status: "escalated",
                metadata: { from_tier: __tier, to_tier: "fallback", from_model: __model.name, to_model: __fb.model.name, exhausted_attempts: __maxAttempts },
            });
            // Swap to the fallback model and run one bounded attempt.
            const __fbModel = __fb.model;
            const __fbController = new AbortController();
            const __fbTimer = setTimeout(() => __fbController.abort(), 120000);
            if (ctx.signal)
                ctx.signal.addEventListener("abort", () => __fbController.abort());
            try {
                const __fbEstimatedTokens = __fbModel.provider.countTokens(__rendered) + (__fbModel.maxOutput || 256);
                __budget.assertCanSpend(__fbEstimatedTokens, __fbModel.costClass);
                const __fbResp = await __fbModel.provider.chat({
                    messages: [{ role: "user", content: __rendered }],
                    model: __fbModel.modelName,
                    temperature: __fbModel.temperature,
                    max_output: __fbModel.maxOutput,
                }, __fbController.signal);
                clearTimeout(__fbTimer);
                const __fbValue = (0, prompts_helpers_1.parseModelOutput)(__fbResp.content, "string");
                const __fbReport = (0, validate_1.validateSchemaOnly)(__fbValue, "string");
                const __fbTokensUsed = (__fbResp.usage?.completion_tokens ?? 0) + (__fbResp.usage?.prompt_tokens ?? 0);
                if (__fbReport.ok) {
                    __budget.charge(__fbTokensUsed || __fbEstimatedTokens, __fbModel.costClass);
                    (0, metrics_1.counter)("cognition.fallback.accepted", { prompt: "code_assist", model: __fbModel.name });
                    await (0, traces_1.writeSpan)({
                        trace_id: ctx.trace_id,
                        workflow: "code_assist",
                        step: "fallback_call",
                        kind: "prompt_call",
                        prompt: "code_assist",
                        model: __fbModel.name,
                        provider: __fbModel.provider.name,
                        input,
                        output: __fbValue,
                        validate_result: "ok",
                        prompt_tokens: __fbResp.usage?.prompt_tokens,
                        completion_tokens: __fbResp.usage?.completion_tokens,
                        latency_ms: Date.now() - __start,
                        status: "ok",
                        metadata: { fallback: true, from_model: __model.name },
                    });
                    return __fbValue;
                }
                // Fallback also failed validation — record and re-throw the original.
                (0, metrics_1.counter)("cognition.fallback.rejected", { prompt: "code_assist", model: __fbModel.name });
                await (0, traces_1.writeSpan)({
                    trace_id: ctx.trace_id,
                    workflow: "code_assist",
                    step: "fallback_call",
                    kind: "validate",
                    prompt: "code_assist",
                    model: __fbModel.name,
                    provider: __fbModel.provider.name,
                    input,
                    output: __fbValue,
                    validate_result: "failed",
                    latency_ms: Date.now() - __start,
                    status: "validate_failed",
                    metadata: { fallback: true, issues: __fbReport.issues.slice(0, 5) },
                });
            }
            catch (__fbErr) {
                clearTimeout(__fbTimer);
                // Fallback model errored. Log + fall through to throw the original.
                const __fbMsg = __fbErr instanceof Error ? __fbErr.message : String(__fbErr);
                logger_1.logger.warn("cognition_fallback_failed", { event: "code_assist", status: "failure", trace_id: ctx.trace_id, metadata: { error: __fbMsg.slice(0, 256) } });
                (0, metrics_1.counter)("cognition.fallback.error", { prompt: "code_assist" });
            }
        }
    }
    throw __lastError ?? new Error("Prompt code_assist failed after retries");
}
