// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — typed prompt callers.
//
// One async function per declared `prompt`. Each function:
//   1. validates input via the prompt's Zod schema (reusing src/schemas.ts)
//   2. resolves the model from a static model_ref OR a router
//   3. loads the template body from src/extensions.ts (extension_point)
//   4. dispatches the call through the provider adapter
//   5. validates the response per prompt.validate (none / schema_only /
//      ast_compiles / custom)
//   6. handles on_invalid: fail / retry / retry_with_repair_prompt /
//      escalate within the prompt's retry budget
//   7. emits a span via the cognition_traces logger
//   8. returns the typed result

import { logger } from "../logger";
import { counter, histogram } from "../metrics";
import { getModel, type ModelEntry } from "../providers";
import { newBudget, budgetEnforced, type BudgetTracker, BudgetExceededError } from "./budget";
import { validateSchemaOnly, validateAstCompiles, validateCustom, type ValidationReport } from "./validate";
import { writeSpan } from "./traces";
import { REPAIRS } from "./repair";
import { cache, deriveKey } from "./cache";
import { createHash } from "crypto";
import { getRouter, type CompiledRouter, type RouteChoice } from "./router";

import { loadExtension, parseModelOutput, type PromptCtx } from "./prompts_helpers";
import { prompt_code_assist } from "./prompt_code_assist";

// Prompt: classify_task_type
// model: TinyClassifier
// validate: schema_only | on_invalid: retry | timeout: 3000ms
async function prompt_classify_task_type(input: Record<string, unknown>, ctx: PromptCtx): Promise<unknown> {
  const __start = Date.now();
  const __model: ModelEntry = getModel("TinyClassifier");
  const __tier = "fixed";
  const __template = loadExtension("tmpl_classify_task");
  const __rendered = String(__template(...Object.values(input)));
  const __messages = [{ role: "user" as const, content: __rendered }];
  const __templateHash = createHash("sha256").update(__rendered).digest("hex").slice(0, 16);
  const __userKey = (() => {
    try { return String(createHash("sha256").update(String(input["user_message"] ?? "")).digest("hex").slice(0, 16)); }
    catch { return ""; }
  })();
  const __cacheKey = deriveKey({
    prompt_name: "classify_task_type",
    model_id: __model.name,
    template_hash: __templateHash + ":" + __userKey,
    output_type: "string",
    input,
  });
  const __hit = await cache.get(__cacheKey);
  if (__hit) {
    logger.info("cognition_prompt_cache_hit", {
      event: "classify_task_type",
      status: "success",
      duration_ms: 0,
      trace_id: ctx.trace_id,
      metadata: { model: __model.name, cache_hit: true }
    });
    await writeSpan({
      trace_id: ctx.trace_id,
      workflow: "classify_task_type",
      step: "cache_lookup",
      kind: "cache_hit",
      prompt: "classify_task_type",
      model: __model.name,
      provider: __model.provider.name,
      input,
      output: __hit.value,
      prompt_tokens: __hit.prompt_tokens ?? undefined,
      completion_tokens: __hit.completion_tokens ?? undefined,
      latency_ms: 0,
      cache_hit: true,
      status: "cache_hit",
    });
    return __hit.value;
  }
  const __budget: BudgetTracker = ctx.budget ?? newBudget(ctx.trace_id);
  const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
  const __maxAttempts = 2;
  let __lastError: unknown = null;
  for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
    const __controller = new AbortController();
    const __timer = setTimeout(() => __controller.abort(), 3000);
    if (ctx.signal) ctx.signal.addEventListener("abort", () => __controller.abort());
    try {
      counter("cognition.prompt_calls", { prompt: "classify_task_type", model: __model.name });
      // Budget gate — refuse if this attempt would push the trace over either ceiling.
      __budget.assertCanSpend(__estimatedTokens, __model.costClass);
      const __resp = await __model.provider.chat({
        model: __model.modelName,
        messages: __messages,
        temperature: __model.temperature,
        top_p: __model.topP ?? undefined,
        max_output: __model.maxOutput,
        stop: __model.stop,
        json: false,
      }, __controller.signal);
      clearTimeout(__timer);
      const __value = parseModelOutput(__resp.content, "string");
      const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
      // validate: schema_only — structural check against string
      const __report: ValidationReport = validateSchemaOnly(__value, "string");
      if (!__report.ok) {
        const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__validationIssues = __report.issues;
        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__badOutput = __value;
        throw __vErr;
      }
      const __elapsed = Date.now() - __start;
      // Phase 3: actual usage — refund the over-estimate, charge the truth.
      const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
      // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
      __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
      // Phase 3: write to cache.
      try {
        await cache.put(__cacheKey, "classify_task_type", __model.name, __value, 600000, {
          prompt_tokens: __resp.usage.prompt_tokens,
          completion_tokens: __resp.usage.completion_tokens,
        });
      } catch (__cacheErr) {
        // Cache write failures are not fatal — log and continue.
        logger.warn("prompt_cache_write_failed", { event: "classify_task_type", status: "rejected", trace_id: ctx.trace_id });
      }
      histogram("cognition.prompt_latency_ms", __elapsed, { prompt: "classify_task_type", model: __model.name });
      logger.info("cognition_prompt_ok", {
        event: "classify_task_type",
        status: "success",
        duration_ms: __elapsed,
        trace_id: ctx.trace_id,
        metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
      });
      await writeSpan({
        trace_id: ctx.trace_id,
        workflow: "classify_task_type",
        step: "chat",
        kind: "prompt_call",
        prompt: "classify_task_type",
        model: __model.name,
        provider: __model.provider.name,
        input,
        output: __value,
        validate_result: "ok",
        confidence: __confidence ?? undefined,
        prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
        completion_tokens: __resp.usage.completion_tokens ?? undefined,
        latency_ms: __elapsed,
        cache_hit: false,
        status: "ok",
        metadata: { attempt: __attempt, tier: __tier },
      });
      return __value;
    } catch (__err: unknown) {
      clearTimeout(__timer);
      __lastError = __err;
      // Budget exceptions are terminal — no retry, no escalate, just bubble.
      if (__err instanceof BudgetExceededError) {
        logger.error("cognition_budget_exceeded", {
          event: "classify_task_type",
          status: "rejected",
          trace_id: ctx.trace_id,
          error_code: "BUDGET_EXCEEDED",
          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
        });
        await writeSpan({
          trace_id: ctx.trace_id,
          workflow: "classify_task_type",
          step: "budget",
          kind: "budget_exceeded",
          prompt: "classify_task_type",
          model: __model.name,
          provider: __model.provider.name,
          input,
          latency_ms: Date.now() - __start,
          status: "budget_exceeded",
          error_code: "BUDGET_EXCEEDED",
          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
        });
        throw __err;
      }
      counter("cognition.prompt_failed", { prompt: "classify_task_type", model: __model.name });
      const __msg = __err instanceof Error ? __err.message : String(__err);
      logger.warn("cognition_prompt_failed", {
        event: "classify_task_type",
        status: "rejected",
        trace_id: ctx.trace_id,
        metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
      });
      {
        const __issues = (__err as Error & { __validationIssues?: string[] }).__validationIssues;
        const __isValidate = Array.isArray(__issues);
        const __isLowConf = typeof (__err as Error & { __lowConfidence?: number }).__lowConfidence === "number";
        const __badOut = (__err as Error & { __badOutput?: unknown }).__badOutput;
        if (!__isLowConf) {
          await writeSpan({
            trace_id: ctx.trace_id,
            workflow: "classify_task_type",
            step: __isValidate ? "validate" : "chat",
            kind: __isValidate ? "validate" : "prompt_call",
            prompt: "classify_task_type",
            model: __model.name,
            provider: __model.provider.name,
            input,
            output: __isValidate ? __badOut : undefined,
            validate_result: __isValidate ? "failed" : undefined,
            latency_ms: Date.now() - __start,
            status: __isValidate ? "validate_failed" : "provider_error",
            error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
            metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
          });
        }
      }
      // on_invalid: retry — fall through to next attempt
      if (__attempt < __maxAttempts) await new Promise(r => setTimeout(r, 100));
    }
  }
  throw __lastError ?? new Error("Prompt classify_task_type failed after retries");
}



// Prompt: compress_history
// model: SmallCoder
// validate: schema_only | on_invalid: retry | timeout: 30000ms
async function prompt_compress_history(input: Record<string, unknown>, ctx: PromptCtx): Promise<unknown> {
  const __start = Date.now();
  const __model: ModelEntry = getModel("SmallCoder");
  const __tier = "fixed";
  const __template = loadExtension("tmpl_compress_history");
  const __rendered = String(__template(...Object.values(input)));
  const __messages = [{ role: "user" as const, content: __rendered }];
  const __budget: BudgetTracker = ctx.budget ?? newBudget(ctx.trace_id);
  const __estimatedTokens = __model.provider.countTokens(__rendered) + (__model.maxOutput || 256);
  const __maxAttempts = 2;
  let __lastError: unknown = null;
  for (let __attempt = 1; __attempt <= __maxAttempts; __attempt++) {
    const __controller = new AbortController();
    const __timer = setTimeout(() => __controller.abort(), 30000);
    if (ctx.signal) ctx.signal.addEventListener("abort", () => __controller.abort());
    try {
      counter("cognition.prompt_calls", { prompt: "compress_history", model: __model.name });
      // Budget gate — refuse if this attempt would push the trace over either ceiling.
      __budget.assertCanSpend(__estimatedTokens, __model.costClass);
      const __resp = await __model.provider.chat({
        model: __model.modelName,
        messages: __messages,
        temperature: __model.temperature,
        top_p: __model.topP ?? undefined,
        max_output: __model.maxOutput,
        stop: __model.stop,
        json: false,
      }, __controller.signal);
      clearTimeout(__timer);
      const __value = parseModelOutput(__resp.content, "string");
      const __confidence = typeof __resp.confidence === "number" ? __resp.confidence : null;
      // validate: schema_only — structural check against string
      const __report: ValidationReport = validateSchemaOnly(__value, "string");
      if (!__report.ok) {
        const __vErr = new Error("validation failed: " + __report.issues.slice(0, 3).join("; "));
        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__validationIssues = __report.issues;
        (__vErr as Error & { __validationIssues?: string[]; __badOutput?: unknown }).__badOutput = __value;
        throw __vErr;
      }
      const __elapsed = Date.now() - __start;
      // Phase 3: actual usage — refund the over-estimate, charge the truth.
      const __actualTokens = (__resp.usage.prompt_tokens || 0) + (__resp.usage.completion_tokens || 0);
      // We pre-charged 0 (assertCanSpend doesn't mutate) so just record the real cost now.
      __budget.charge(__actualTokens || __estimatedTokens, __model.costClass);
      histogram("cognition.prompt_latency_ms", __elapsed, { prompt: "compress_history", model: __model.name });
      logger.info("cognition_prompt_ok", {
        event: "compress_history",
        status: "success",
        duration_ms: __elapsed,
        trace_id: ctx.trace_id,
        metadata: { model: __model.name, attempt: __attempt, tier: __tier, prompt_tokens: __resp.usage.prompt_tokens, completion_tokens: __resp.usage.completion_tokens, cache_hit: false, confidence: __confidence }
      });
      await writeSpan({
        trace_id: ctx.trace_id,
        workflow: "compress_history",
        step: "chat",
        kind: "prompt_call",
        prompt: "compress_history",
        model: __model.name,
        provider: __model.provider.name,
        input,
        output: __value,
        validate_result: "ok",
        confidence: __confidence ?? undefined,
        prompt_tokens: __resp.usage.prompt_tokens ?? undefined,
        completion_tokens: __resp.usage.completion_tokens ?? undefined,
        latency_ms: __elapsed,
        cache_hit: false,
        status: "ok",
        metadata: { attempt: __attempt, tier: __tier },
      });
      return __value;
    } catch (__err: unknown) {
      clearTimeout(__timer);
      __lastError = __err;
      // Budget exceptions are terminal — no retry, no escalate, just bubble.
      if (__err instanceof BudgetExceededError) {
        logger.error("cognition_budget_exceeded", {
          event: "compress_history",
          status: "rejected",
          trace_id: ctx.trace_id,
          error_code: "BUDGET_EXCEEDED",
          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed }
        });
        await writeSpan({
          trace_id: ctx.trace_id,
          workflow: "compress_history",
          step: "budget",
          kind: "budget_exceeded",
          prompt: "compress_history",
          model: __model.name,
          provider: __model.provider.name,
          input,
          latency_ms: Date.now() - __start,
          status: "budget_exceeded",
          error_code: "BUDGET_EXCEEDED",
          metadata: { kind: __err.kind, limit: __err.limit, observed: __err.observed },
        });
        throw __err;
      }
      counter("cognition.prompt_failed", { prompt: "compress_history", model: __model.name });
      const __msg = __err instanceof Error ? __err.message : String(__err);
      logger.warn("cognition_prompt_failed", {
        event: "compress_history",
        status: "rejected",
        trace_id: ctx.trace_id,
        metadata: { model: __model.name, attempt: __attempt, error: __msg.slice(0, 256) }
      });
      {
        const __issues = (__err as Error & { __validationIssues?: string[] }).__validationIssues;
        const __isValidate = Array.isArray(__issues);
        const __isLowConf = typeof (__err as Error & { __lowConfidence?: number }).__lowConfidence === "number";
        const __badOut = (__err as Error & { __badOutput?: unknown }).__badOutput;
        if (!__isLowConf) {
          await writeSpan({
            trace_id: ctx.trace_id,
            workflow: "compress_history",
            step: __isValidate ? "validate" : "chat",
            kind: __isValidate ? "validate" : "prompt_call",
            prompt: "compress_history",
            model: __model.name,
            provider: __model.provider.name,
            input,
            output: __isValidate ? __badOut : undefined,
            validate_result: __isValidate ? "failed" : undefined,
            latency_ms: Date.now() - __start,
            status: __isValidate ? "validate_failed" : "provider_error",
            error_code: __isValidate ? "VALIDATE_FAILED" : "PROVIDER_ERROR",
            metadata: { attempt: __attempt, error: __msg.slice(0, 256), issues: __issues?.slice(0, 5) },
          });
        }
      }
      // on_invalid: retry — fall through to next attempt
      if (__attempt < __maxAttempts) await new Promise(r => setTimeout(r, 500));
    }
  }
  throw __lastError ?? new Error("Prompt compress_history failed after retries");
}

export type PromptFn = (input: Record<string, unknown>, ctx: PromptCtx) => Promise<unknown>;

export const PROMPTS: Record<string, PromptFn> = {
  "classify_task_type": prompt_classify_task_type,
  "code_assist": prompt_code_assist,
  "compress_history": prompt_compress_history,
};

export function getPrompt(name: string): PromptFn {
  const fn = PROMPTS[name];
  if (!fn) throw new Error(`Unknown prompt: ${name}`);
  return fn;
}

/**
 * Find the first prompt that looks like a summariser by convention:
 * any prompt whose name contains "summar". Used by the
 * compress_context cognition primitive when the user has not specified
 * an explicit summariser.
 */
export function findSummarizer(): PromptFn | null {
  for (const name of Object.keys(PROMPTS).sort()) {
    if (/summar/i.test(name)) return PROMPTS[name];
  }
  return null;
}
