// Generated by MarrowScript compiler. DO NOT EDIT.
import { counter } from "../metrics";

export interface ValidationReport {
  ok: boolean;
  /** Concrete issues — used to seed repair prompts. */
  issues: string[];
}

/** Strip enum-style declared types like `enum<["a","b"]>` and return the literal set, or null. */
export function parseEnumDecl(declared: string): string[] | null {
  const m = declared.match(/^enum<\[(.+)\]>$/);
  if (!m) return null;
  const items: string[] = [];
  let buf = "";
  let depth = 0;
  for (const ch of m[1]) {
    if (ch === "[" || ch === "{" || ch === "(") depth++;
    if (ch === "]" || ch === "}" || ch === ")") depth--;
    if (ch === "," && depth === 0) { items.push(buf.trim()); buf = ""; }
    else buf += ch;
  }
  if (buf.trim()) items.push(buf.trim());
  return items.map(s => {
    try { return JSON.parse(s); }
    catch { return s.replace(/^["']|["']$/g, ""); }
  });
}

/** True when the declared type is a recognised primitive. */
export function declaredPrimitiveCheck(declared: string, value: unknown): string | null {
  switch (declared) {
    case "string":
      if (typeof value !== "string") return `expected string, got ${typeof value}`;
      return value.length === 0 ? "empty string" : null;
    case "int": case "uint": case "float":
      if (typeof value !== "number" || !Number.isFinite(value)) return `expected number, got ${typeof value}`;
      if (declared === "uint" && value < 0) return "expected uint, got negative";
      if (declared === "int" && !Number.isInteger(value)) return "expected int, got non-integer";
      return null;
    case "bool":
      return typeof value === "boolean" ? null : `expected bool, got ${typeof value}`;
    case "json":
      return null;
    default:
      return null;
  }
}

export function validateSchemaOnly(value: unknown, outputType: string): ValidationReport {
  const issues: string[] = [];
  if (outputType === "File") {
    fileShapeIssues(value, issues, "");
    return finalize(issues, "file");
  }
  if (/^list<\s*File\s*>$/.test(outputType)) {
    if (!Array.isArray(value)) {
      issues.push(`expected list<File>, got ${typeof value}`);
      return finalize(issues, "files");
    }
    if (value.length === 0) {
      issues.push("expected at least one File, got empty array");
      return finalize(issues, "files");
    }
    const seen = new Set<string>();
    for (let i = 0; i < value.length; i++) {
      fileShapeIssues(value[i], issues, `file[${i}]: `);
      const f = value[i] as { path?: unknown };
      if (typeof f?.path === "string") {
        if (seen.has(f.path)) issues.push(`file[${i}]: duplicate path "${f.path}"`);
        seen.add(f.path);
      }
    }
    return finalize(issues, "files");
  }
  const enumValues = parseEnumDecl(outputType);
  if (enumValues) {
    if (typeof value !== "string") {
      issues.push(`expected one of [${enumValues.join(", ")}], got ${typeof value}`);
    } else if (!enumValues.includes(value)) {
      issues.push(`value "${value.slice(0, 64)}" is not in [${enumValues.join(", ")}]`);
    }
    return finalize(issues, "enum");
  }
  const listMatch = outputType.match(/^list<(.+)>$/);
  if (listMatch) {
    if (!Array.isArray(value)) {
      issues.push(`expected list<${listMatch[1]}>, got ${typeof value}`);
    } else {
      const inner = listMatch[1];
      for (let i = 0; i < value.length; i++) {
        const issue = declaredPrimitiveCheck(inner, value[i]);
        if (issue) issues.push(`item[${i}]: ${issue}`);
      }
    }
    return finalize(issues, "list");
  }
  const issue = declaredPrimitiveCheck(outputType, value);
  if (issue) issues.push(issue);
  return finalize(issues, "primitive");
}

export function fileShapeIssues(value: unknown, issues: string[], prefix: string): void {
  if (!value || typeof value !== "object") {
    issues.push(`${prefix}expected File record, got ${typeof value}`);
    return;
  }
  const v = value as { path?: unknown; content?: unknown; kind?: unknown };
  if (typeof v.path !== "string" || v.path.length === 0) {
    issues.push(`${prefix}File.path must be a non-empty string`);
  } else if (v.path.includes("..") || v.path.startsWith("/") || /^[A-Za-z]:/.test(v.path)) {
    issues.push(`${prefix}File.path must be a relative path without ".." segments`);
  }
  if (typeof v.content !== "string") {
    issues.push(`${prefix}File.content must be a string`);
  } else if (v.content.length === 0) {
    issues.push(`${prefix}File.content is empty`);
  }
  if (v.kind !== undefined && typeof v.kind !== "string") {
    issues.push(`${prefix}File.kind must be a string when present`);
  }
}

export function finalize(issues: string[], kind: string): ValidationReport {
  if (issues.length > 0) {
    counter("cognition.validate.failed", { mode: "schema_only", kind });
  } else {
    counter("cognition.validate.passed", { mode: "schema_only", kind });
  }
  return { ok: issues.length === 0, issues };
}
