// Generated by MarrowScript compiler. DO NOT EDIT.
import { counter } from "../metrics";
import { logger } from "../logger";
import { type ValidationReport } from "./validate_schema";

export async function validateAstCompiles(value: unknown): Promise<ValidationReport> {
  if (Array.isArray(value)) {
    return validateFileList(value);
  }
  if (value && typeof value === "object" && "path" in (value as object) && "content" in (value as object)) {
    const f = value as { path: string; content: unknown };
    return validateSingleFile(f);
  }
  if (typeof value !== "string" || value.trim().length === 0) {
    counter("cognition.validate.failed", { mode: "ast_compiles", kind: "empty" });
    return { ok: false, issues: ["output must be a non-empty TypeScript string"] };
  }
  return validateTypeScriptString(value);
}

async function validateSingleFile(f: { path: string; content: unknown }): Promise<ValidationReport> {
  if (typeof f.content !== "string" || f.content.trim().length === 0) {
    counter("cognition.validate.failed", { mode: "ast_compiles", kind: "empty_file" });
    return { ok: false, issues: [`${f.path}: content must be a non-empty TypeScript string`] };
  }
  const inner = await validateTypeScriptString(f.content);
  if (inner.ok) return inner;
  return { ok: false, issues: inner.issues.map(i => `${f.path}: ${i}`) };
}

async function validateFileList(files: unknown[]): Promise<ValidationReport> {
  if (files.length === 0) {
    counter("cognition.validate.failed", { mode: "ast_compiles", kind: "empty_list" });
    return { ok: false, issues: ["file list is empty"] };
  }
  const aggregated: string[] = [];
  for (let i = 0; i < files.length; i++) {
    const f = files[i] as { path?: unknown; content?: unknown };
    if (!f || typeof f !== "object" || typeof f.path !== "string") {
      aggregated.push(`file[${i}]: invalid shape; expected { path, content }`);
      continue;
    }
    const path = f.path;
    const isTs = /\.(ts|tsx|cts|mts)$/i.test(path);
    if (!isTs) continue;
    const r = await validateSingleFile({ path, content: f.content });
    if (!r.ok) aggregated.push(...r.issues);
  }
  if (aggregated.length > 0) {
    counter("cognition.validate.failed", { mode: "ast_compiles", kind: "file_list" });
  } else {
    counter("cognition.validate.passed", { mode: "ast_compiles", kind: "file_list" });
  }
  return { ok: aggregated.length === 0, issues: aggregated };
}

async function validateTypeScriptString(value: string): Promise<ValidationReport> {
  const candidate = pickLargestTsSection(extractFencedTypeScript(value));
  let ts: typeof import("typescript") | null = null;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    ts = require("typescript") as typeof import("typescript");
  } catch {
    counter("cognition.validate.skipped", { mode: "ast_compiles" });
    return { ok: true, issues: ["typescript module not installed — ast_compiles skipped"] };
  }

  const sf = ts.createSourceFile("__model_output.ts", candidate, ts.ScriptTarget.Latest, true);
  const issues: string[] = [];

  const parseDiags = (sf as unknown as { parseDiagnostics?: ReadonlyArray<import("typescript").Diagnostic> }).parseDiagnostics ?? [];
  for (const d of parseDiags) {
    issues.push(ts.flattenDiagnosticMessageText(d.messageText, "\n"));
  }

  if (issues.length === 0) {
    try {
      const compilerOptions: import("typescript").CompilerOptions = {
        target: ts.ScriptTarget.ES2022,
        module: ts.ModuleKind.CommonJS,
        strict: false,
        noResolve: true,
        skipLibCheck: true,
        skipDefaultLibCheck: true,
        noEmit: true,
        allowJs: true,
        noUnusedLocals: false,
        noUnusedParameters: false,
        noImplicitAny: false,
      };
      const stubLib = [
        "declare var console: { log(...a: unknown[]): void; warn(...a: unknown[]): void; error(...a: unknown[]): void; info(...a: unknown[]): void; debug(...a: unknown[]): void };",
        "declare var process: { cwd(): string; env: Record<string, string | undefined>; argv: string[]; exit(code?: number): never };",
        "declare var Buffer: { from(s: string, e?: string): { toString(e?: string): string } };",
        "declare var setTimeout: (cb: () => void, ms: number) => unknown;",
        "declare var clearTimeout: (h: unknown) => void;",
        "declare var setInterval: (cb: () => void, ms: number) => unknown;",
        "declare var clearInterval: (h: unknown) => void;",
        "declare var require: (m: string) => unknown;",
        "declare var module: unknown; declare var exports: unknown; declare var __dirname: string; declare var __filename: string;",
        "declare var globalThis: { fetch: (url: string, init?: unknown) => Promise<Response> } & Record<string, unknown>;",
        "declare var Number: { isInteger(v: unknown): boolean; isFinite(v: unknown): boolean; parseFloat(s: string): number; parseInt(s: string, r?: number): number };",
        "declare var Math: { floor(n: number): number; ceil(n: number): number; round(n: number): number; min(...n: number[]): number; max(...n: number[]): number; abs(n: number): number; pow(b: number, e: number): number; random(): number };",
        "declare var JSON: { parse(s: string): unknown; stringify(v: unknown, r?: unknown, s?: unknown): string };",
        "declare var Symbol: { for(s: string): symbol; iterator: symbol };",
        "interface Iterator<T> { next(): { value: T; done: boolean } }",
        "interface Iterable<T> { [Symbol.iterator](): Iterator<T> }",
        "interface ArrayLike<T> { readonly length: number; readonly [n: number]: T }",
        "interface Map<K, V> { get(k: K): V | undefined; set(k: K, v: V): this; has(k: K): boolean; delete(k: K): boolean; clear(): void; size: number; keys(): Iterator<K>; values(): Iterator<V>; entries(): Iterator<[K, V]>; forEach(cb: (v: V, k: K) => void): void }",
        "interface MapConstructor { new <K, V>(entries?: Iterable<[K, V]>): Map<K, V> }",
        "declare var Map: MapConstructor;",
        "interface Set<T> { add(v: T): this; has(v: T): boolean; delete(v: T): boolean; clear(): void; size: number; values(): Iterator<T>; forEach(cb: (v: T) => void): void }",
        "interface SetConstructor { new <T>(values?: Iterable<T>): Set<T> }",
        "declare var Set: SetConstructor;",
        "interface Promise<T> { then<U>(onFulfilled?: (v: T) => U | Promise<U>, onRejected?: (e: unknown) => U | Promise<U>): Promise<U>; catch<U>(onRejected: (e: unknown) => U | Promise<U>): Promise<U>; finally(cb: () => void): Promise<T> }",
        "interface PromiseConstructor { new <T>(executor: (resolve: (v: T) => void, reject: (e: unknown) => void) => void): Promise<T>; all<T>(p: Promise<T>[]): Promise<T[]>; resolve<T>(v: T): Promise<T>; reject(e: unknown): Promise<never> }",
        "declare var Promise: PromiseConstructor;",
        "interface Array<T> { length: number; [n: number]: T; push(...items: T[]): number; pop(): T | undefined; map<U>(cb: (v: T, i: number) => U): U[]; filter(cb: (v: T, i: number) => boolean): T[]; forEach(cb: (v: T, i: number) => void): void; slice(s?: number, e?: number): T[]; join(sep?: string): string; includes(v: T): boolean; find(cb: (v: T) => boolean): T | undefined; indexOf(v: T): number; concat(...items: T[]): T[]; reverse(): T[]; sort(cb?: (a: T, b: T) => number): T[]; some(cb: (v: T) => boolean): boolean; every(cb: (v: T) => boolean): boolean; reduce<U>(cb: (acc: U, v: T) => U, init: U): U; flat<U>(): U[] }",
        "interface ArrayConstructor { new <T>(length: number): T[]; new <T>(...items: T[]): T[]; isArray(v: unknown): boolean; from<T>(v: Iterable<T> | ArrayLike<T>): T[] }",
        "declare var Array: ArrayConstructor;",
        "interface String { length: number; [n: number]: string; charAt(i: number): string; charCodeAt(i: number): number; concat(...s: string[]): string; includes(s: string): boolean; indexOf(s: string): number; lastIndexOf(s: string): number; match(re: unknown): unknown; replace(re: unknown, r: string): string; slice(s?: number, e?: number): string; split(sep?: string | unknown): string[]; substring(s: number, e?: number): string; toLowerCase(): string; toUpperCase(): string; trim(): string; startsWith(s: string): boolean; endsWith(s: string): boolean; repeat(n: number): string; padStart(n: number, p?: string): string; padEnd(n: number, p?: string): string; normalize(): string }",
        "interface StringConstructor { (v: unknown): string; new (v: unknown): String; fromCharCode(...codes: number[]): string }",
        "declare var String: StringConstructor;",
        "interface Date { toISOString(): string; getTime(): number; toString(): string }",
        "interface DateConstructor { new (): Date; new (ms: number): Date; new (s: string): Date; now(): number }",
        "declare var Date: DateConstructor;",
        "interface ObjectConstructor { keys(o: object): string[]; values(o: object): unknown[]; entries(o: object): [string, unknown][]; assign<T>(t: T, ...s: unknown[]): T; freeze<T>(o: T): T; create(proto: object | null, props?: Record<string, unknown>): object }",
        "declare var Object: ObjectConstructor;",
        "interface Error { message: string; stack?: string; name: string }",
        "interface ErrorConstructor { new (m?: string): Error; (m?: string): Error; captureStackTrace?(e: unknown, c?: unknown): void }",
        "declare var Error: ErrorConstructor;",
        "interface RegExp { test(s: string): boolean; exec(s: string): string[] | null; source: string; flags: string }",
        "interface RegExpConstructor { new (p: string, f?: string): RegExp; (p: string, f?: string): RegExp }",
        "declare var RegExp: RegExpConstructor;",
        "type Record<K extends string | number | symbol, V> = { [P in K]: V };",
        "type Partial<T> = { [P in keyof T]?: T[P] };",
        "type Required<T> = { [P in keyof T]-?: T[P] };",
        "type Readonly<T> = { readonly [P in keyof T]: T[P] };",
        "type Pick<T, K extends keyof T> = { [P in K]: T[P] };",
        "type Omit<T, K extends string | number | symbol> = { [P in keyof T as P extends K ? never : P]: T[P] };",
        "type Awaited<T> = T extends Promise<infer U> ? U : T;",
        "type ReturnType<T extends (...a: unknown[]) => unknown> = T extends (...a: unknown[]) => infer R ? R : unknown;",
        "type Parameters<T extends (...a: unknown[]) => unknown> = T extends (...a: infer P) => unknown ? P : never;",
        "interface Headers { get(name: string): string | null; has(name: string): boolean; set(name: string, value: string): void; append(name: string, value: string): void; delete(name: string): void }",
        "interface Response { readonly ok: boolean; readonly status: number; readonly statusText: string; readonly headers: Headers; readonly url: string; text(): Promise<string>; json(): Promise<unknown>; arrayBuffer(): Promise<ArrayBuffer>; clone(): Response }",
        "interface RequestInit { method?: string; headers?: Headers | Record<string, string>; body?: string | unknown; signal?: unknown; credentials?: 'omit' | 'include' | 'same-origin'; mode?: 'cors' | 'no-cors' | 'same-origin'; redirect?: 'follow' | 'error' | 'manual' }",
        "declare var fetch: (url: string, init?: RequestInit) => Promise<Response>;",
        "interface ArrayBuffer { readonly byteLength: number; slice(begin: number, end?: number): ArrayBuffer }",
        "declare var ArrayBuffer: { new (length: number): ArrayBuffer };",
        "declare module 'fs' { export function readFileSync(p: string, e?: string): string; export function writeFileSync(p: string, d: string | unknown, e?: string | unknown): void; export function existsSync(p: string): boolean; export function mkdirSync(p: string, opts?: { recursive?: boolean }): void; export function readdirSync(p: string): string[]; export function statSync(p: string): { isDirectory(): boolean; isFile(): boolean; size: number }; export function unlinkSync(p: string): void; export const promises: { readFile(p: string, e?: string): Promise<string>; writeFile(p: string, d: string | unknown, e?: string): Promise<void>; mkdir(p: string, opts?: { recursive?: boolean }): Promise<void> } }",
        "declare module 'path' { export function join(...parts: string[]): string; export function resolve(...parts: string[]): string; export function basename(p: string, ext?: string): string; export function dirname(p: string): string; export function extname(p: string): string; export function relative(from: string, to: string): string; export const sep: string; export const delimiter: string }",
        "declare module 'crypto' { export function randomUUID(): string; export function randomBytes(n: number): { toString(e?: string): string }; export function createHash(alg: string): { update(d: string | unknown): { digest(e?: string): string } }; export function createHmac(alg: string, key: string): { update(d: string): { digest(e?: string): string } } }",
        "declare module 'child_process' { export function exec(cmd: string, cb: (err: Error | null, stdout: string, stderr: string) => void): unknown; export function execSync(cmd: string, opts?: { encoding?: string; cwd?: string }): string; export function execFile(cmd: string, args: string[], cb: (err: Error | null, stdout: string, stderr: string) => void): unknown; export function spawn(cmd: string, args: string[], opts?: { cwd?: string }): unknown }",
        "declare module 'http' { export function createServer(handler: (req: unknown, res: unknown) => void): { listen(port: number, cb?: () => void): void; close(cb?: () => void): void }; export function request(opts: unknown, cb: (res: unknown) => void): unknown }",
        "declare module 'https' { export function request(opts: unknown, cb: (res: unknown) => void): unknown; export function get(url: string, cb: (res: unknown) => void): unknown }",
        "declare module 'os' { export function platform(): string; export function arch(): string; export function tmpdir(): string; export function homedir(): string; export function cpus(): unknown[]; export function totalmem(): number; export function freemem(): number }",
        "declare module 'url' { export class URL { constructor(input: string, base?: string); href: string; origin: string; protocol: string; host: string; pathname: string; search: string; searchParams: { get(k: string): string | null; set(k: string, v: string): void } } }",
        "declare module 'events' { export class EventEmitter { on(event: string, cb: (...a: unknown[]) => void): this; off(event: string, cb: (...a: unknown[]) => void): this; emit(event: string, ...a: unknown[]): boolean; once(event: string, cb: (...a: unknown[]) => void): this; removeAllListeners(event?: string): this } }",
        "declare module 'stream' { export class Readable { read(size?: number): unknown; pipe<T>(dest: T): T; on(event: string, cb: (...a: unknown[]) => void): this } export class Writable { write(chunk: unknown): boolean; end(chunk?: unknown): void; on(event: string, cb: (...a: unknown[]) => void): this } }",
        "declare module 'util' { export function promisify<T>(fn: T): T; export function inspect(v: unknown, opts?: unknown): string; export function format(...a: unknown[]): string }",
      ].join("\n");
      const stubSf = ts.createSourceFile("__lib.d.ts", stubLib, ts.ScriptTarget.ES2022, true);
      const host: import("typescript").CompilerHost = {
        fileExists: (p) => p === "__model_output.ts" || p === "__lib.d.ts",
        readFile: (p) => p === "__model_output.ts" ? candidate : p === "__lib.d.ts" ? stubLib : undefined,
        writeFile: () => {},
        getSourceFile: (p) => p === "__model_output.ts" ? sf : p === "__lib.d.ts" ? stubSf : undefined,
        getDefaultLibFileName: () => "__lib.d.ts",
        useCaseSensitiveFileNames: () => true,
        getCanonicalFileName: (p) => p,
        getCurrentDirectory: () => "",
        getNewLine: () => "\n",
      };
      const program = ts.createProgram(["__model_output.ts", "__lib.d.ts"], compilerOptions, host);

      const STRICT_IMPORTS = process.env.LLM_VALIDATE_STRICT_IMPORTS === "1";
      const SOFT_CODES = new Set<number>(STRICT_IMPORTS ? [6133] : [2307, 2305, 6133, 2792]);
      const diags = [
        ...program.getSyntacticDiagnostics(sf),
        ...program.getSemanticDiagnostics(sf),
      ];
      const softNotes: string[] = [];
      for (const d of diags) {
        const msg = ts.flattenDiagnosticMessageText(d.messageText, "\n");
        const formatted = `TS${d.code}: ${msg}`;
        if (SOFT_CODES.has(d.code)) {
          softNotes.push(formatted);
        } else {
          issues.push(formatted);
        }
      }
      if (softNotes.length > 0) {
        logger.info("validate_ast_soft_notes", { event: "validate", status: "success", metadata: { count: softNotes.length, sample: softNotes.slice(0, 3) } });
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      logger.warn("validate_ast_compile_failed", { event: "validate", status: "rejected", metadata: { error: msg.slice(0, 256) } });
      issues.push(`validator threw: ${msg.slice(0, 200)}`);
    }
  }

  if (issues.length > 0) counter("cognition.validate.failed", { mode: "ast_compiles", kind: "diag" });
  else counter("cognition.validate.passed", { mode: "ast_compiles", kind: "clean" });
  return { ok: issues.length === 0, issues };
}

function pickLargestTsSection(value: string): string {
  const headerRe = /^\s*(?:\/\/|\/\*)\s*(?:File:|path:|=+)?\s*[a-zA-Z0-9_\-./]+\.(?:ts|tsx|js|jsx|mts|cts)\s*(?:=+\s*)?(?:\*\/)?\s*$/;
  const lines = value.split(/\r?\n/);
  const sections: string[] = [];
  let current: string[] = [];
  for (const line of lines) {
    if (headerRe.test(line)) {
      if (current.length > 0) sections.push(current.join("\n"));
      current = [];
    } else {
      current.push(line);
    }
  }
  if (current.length > 0) sections.push(current.join("\n"));
  if (sections.length <= 1) return value;
  let best = sections[0];
  for (let i = 1; i < sections.length; i++) {
    if (sections[i].length > best.length) best = sections[i];
  }
  return best;
}

function extractFencedTypeScript(value: string): string {
  const fenceRe = /```([a-zA-Z]*)\s*\n([\s\S]*?)\n```/g;
  const tsFences: string[] = [];
  const untaggedFences: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = fenceRe.exec(value)) !== null) {
    const lang = (m[1] || "").toLowerCase();
    const body = m[2];
    if (lang === "typescript" || lang === "ts" || lang === "tsx") {
      tsFences.push(body);
    } else if (lang === "") {
      untaggedFences.push(body);
    }
  }
  const pool = tsFences.length > 0 ? tsFences : untaggedFences;
  if (pool.length === 0) return value;
  let best = pool[0];
  for (let i = 1; i < pool.length; i++) {
    if (pool[i].length > best.length) best = pool[i];
  }
  return best;
}

export function validateCustom(value: unknown, validatorFn: (value: unknown) => unknown): ValidationReport {
  try {
    const raw = validatorFn(value);
    if (raw && typeof raw === "object" && "ok" in (raw as Record<string, unknown>)) {
      const r = raw as { ok?: unknown; issues?: unknown };
      const ok = Boolean(r.ok);
      const issues = Array.isArray(r.issues) ? (r.issues as unknown[]).map(String) : [];
      counter(ok ? "cognition.validate.passed" : "cognition.validate.failed", { mode: "custom", kind: "structured" });
      return { ok, issues };
    }
    const ok = Boolean(raw);
    counter(ok ? "cognition.validate.passed" : "cognition.validate.failed", { mode: "custom", kind: "truthy" });
    return { ok, issues: ok ? [] : ["custom validator rejected output"] };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    counter("cognition.validate.failed", { mode: "custom", kind: "threw" });
    return { ok: false, issues: [`custom validator threw: ${msg.slice(0, 200)}`] };
  }
}
