"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.validateCustom = exports.validateAstCompiles = exports.validateSchemaOnly = void 0;
// Generated by MarrowScript compiler. DO NOT EDIT.
const validate_schema_1 = require("./validate_schema");
Object.defineProperty(exports, "validateSchemaOnly", { enumerable: true, get: function () { return validate_schema_1.validateSchemaOnly; } });
const validate_runner_1 = require("./validate_runner");
Object.defineProperty(exports, "validateAstCompiles", { enumerable: true, get: function () { return validate_runner_1.validateAstCompiles; } });
Object.defineProperty(exports, "validateCustom", { enumerable: true, get: function () { return validate_runner_1.validateCustom; } });
